# Generated by Django 5.1.3 on 2024-12-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0006_alter_review_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
